steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-service-test'
      - '--image=gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=1024Mi'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_NAME=$(gcloud secrets versions access latest --secret=db_name),DB_PORT=$(gcloud secrets versions access latest --secret=db_port),DB_USER=$(gcloud secrets versions access latest --secret=db_user),DB_PASS=$(gcloud secrets versions access latest --secret=db_pass),DB_HOST=$(gcloud secrets versions access latest --secret=db_host),CLIENT_ID:$(gcloud secrets versions access latest --secret=client_id),CLIENT_SECRET=$(gcloud secrets versions access latest --secret=client_secret),MY_EMAIL=$(gcloud secrets versions access latest --secret=my_email),RATE_LIMIT=$(gcloud secrets versions access latest --secret=rate_limit),REDIRECT_URI=$(gcloud secrets versions access latest --secret=redirect_uri),REFRESH_TOKEN=$(gcloud secrets versions access latest --secret=refresh_token),SECRET_KEY=$(gcloud secrets versions access latest --secret=secret_key),SECRET_PASSWORD_SUPERADMIN=$(gcloud secrets versions access latest --secret=secret_password_superadmin)'
images:
  - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
logsBucket: 'gs://bangkitcapstone-bloomy-bucket/logs'