steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-service-test'
      - '--image=gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=1024Mi'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_NAME=projects/$PROJECT_ID/secrets/latest:db_name,DB_PORT=projects/$PROJECT_ID/secrets/latest:db_port,DB_USER=projects/$PROJECT_ID/secrets/latest:db_user,DB_PASS=projects/$PROJECT_ID/secrets/latest:db_pass,DB_HOST=projects/$PROJECT_ID/secrets/latest:db_host,CLIENT_ID=projects/$PROJECT_ID/secrets/latest:client_id,CLIENT_SECRET=projects/$PROJECT_ID/secrets/latest:client_secret,MY_EMAIL=projects/$PROJECT_ID/secrets/latest:my_email,RATE_LIMIT=projects/$PROJECT_ID/secrets/latest:rate_limit,REDIRECT_URI=projects/$PROJECT_ID/secrets/latest:redirect_uri,REFRESH_TOKEN=projects/$PROJECT_ID/secrets/latest:refresh_token,SECRET_KEY=projects/$PROJECT_ID/secrets/latest:secret_key,SECRET_PASSWORD_SUPERADMIN=projects/$PROJECT_ID/secrets/latest:secret_password_superadmin'
images:
  - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
logsBucket: 'gs://bangkitcapstone-bloomy-bucket/logs'