steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-service-test'
      - '--image=gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=1024Mi'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_NAME=projects/$PROJECT_ID/secrets/latest/versions/db_name:latest,DB_PORT=projects/$PROJECT_ID/secrets/latest/versions/db_port:latest,DB_USER=projects/$PROJECT_ID/secrets/latest/versions/db_user:latest,DB_PASS=projects/$PROJECT_ID/secrets/latest/versions/db_pass:latest,DB_HOST=projects/$PROJECT_ID/secrets/latest/versions/db_host:latest,CLIENT_ID=projects/$PROJECT_ID/secrets/latest/versions/client_id:latest,CLIENT_SECRET=projects/$PROJECT_ID/secrets/latest/versions/client_secret:latest,MY_EMAIL=projects/$PROJECT_ID/secrets/latest/versions/my_email:latest,RATE_LIMIT=projects/$PROJECT_ID/secrets/latest/versions/rate_limit:latest,REDIRECT_URI=projects/$PROJECT_ID/secrets/latest/versions/redirect_uri:latest,REFRESH_TOKEN=projects/$PROJECT_ID/secrets/latest/versions/refresh_token:latest,SECRET_KEY=projects/$PROJECT_ID/secrets/latest/versions/secret_key:latest,SECRET_PASSWORD_SUPERADMIN=projects/$PROJECT_ID/secrets/latest/versions/secret_password_superadmin'
images:
  - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
logsBucket: 'gs://bangkitcapstone-bloomy-bucket/logs'