steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-service-test'
      - '--image=gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=1024Mi'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_NAME=projects/$PROJECT_ID/secrets/db_name/versions/latest,DB_PORT=projects/$PROJECT_ID/secrets/db_port/versions/latest,DB_USER=projects/$PROJECT_ID/secrets/db_user/versions/latest,DB_PASS=projects/$PROJECT_ID/secrets/db_pass/versions/latest,DB_HOST=projects/$PROJECT_ID/secrets/db_host/versions/latest,CLIENT_ID=projects/$PROJECT_ID/secrets/client_id/versions/latest,CLIENT_SECRET=projects/$PROJECT_ID/secrets/client_secret/versions/latest,MY_EMAIL=projects/$PROJECT_ID/secrets/my_email/versions/latest,RATE_LIMIT=projects/$PROJECT_ID/secrets/rate_limit/versions/latest,REDIRECT_URI=projects/$PROJECT_ID/secrets/redirect_uri/versions/latest,REFRESH_TOKEN=projects/$PROJECT_ID/secrets/refresh_token/versions/latest,SECRET_KEY=projects/$PROJECT_ID/secrets/secret_key/versions/latest,SECRET_PASSWORD_SUPERADMIN=projects/$PROJECT_ID/secrets/secret_password_superadmin'
images:
  - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
logsBucket: 'gs://bangkitcapstone-bloomy-bucket/logs'