steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-service-test'
      - '--image=gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=1024Mi'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_NAME=latest:db_name,DB_PORT=latest:db_port,DB_USER=latest:db_user,DB_PASS=latest:db_pass,DB_HOST=latest:db_host,CLIENT_ID=latest:client_id,CLIENT_SECRET=latest:client_secret,MY_EMAIL=latest:my_email,RATE_LIMIT=latest:rate_limit,REDIRECT_URI=latest:redirect_uri,REFRESH_TOKEN=latest:refresh_token,SECRET_KEY=latest:secret_key,SECRET_PASSWORD_SUPERADMIN=latest:secret_password_superadmin'
images:
  - 'gcr.io/$PROJECT_ID/bloomy-service-test:$COMMIT_SHA'
logsBucket: 'gs://bangkitcapstone-bloomy-bucket/logs'